shinyUI(fluidPage(
  titlePanel("Item Response Theory"),
  sidebarLayout(sidebarPanel( "Parameters",
  sliderInput("a1","a1",
              min = -3,
              max = 3,
              value = 1),
  sliderInput("b1","b1",
              min = -3,
              max = 3,
              value = 0),
  sliderInput("c1","c1",
              min = 0,
              max = 1,
              value =0),
  sliderInput("a2","a2",
              min = -3,
              max = 3,
              value = 1),
  sliderInput("b2","b2",
              min = -3,
              max = 3,
              value = 1),
  sliderInput("c2","c2",
              min = 0,
              max = 1,
              value =0),
  sliderInput("a3","a3",
              min = -3,
              max = 3,
              value = 1),
  sliderInput("b3","b3",
              min = -3,
              max = 3,
              value = -1),
  sliderInput("c3","c3",
              min = 0,
              max = 1,
              value =0),
  sliderInput("theta","theta",
              min = -3,
              max = 3,
              value = 0)
  ),
  mainPanel(
    tabsetPanel(
      tabPanel("A Single Item/Person",plotOutput("IRF"),tags$br(),
               plotOutput("IIF"),tags$br(),plotOutput("PRF")),
      tabPanel("Three Items",plotOutput("IRF2"),tags$br(),plotOutput("TCC"),tags$br(),plotOutput("TIF"))
))
)))
